name: Publish NPM packages
description: Publishes all NPM packages found in the repository, if their version has incremented
author: IgorNovozhilov

inputs:
  token:
    description: NPM access token for publishing a package
    required: true

runs:
  using: node16
  pre: setup-own-dependencies.cjs
  main: npm-publish.cjs
