name: Publish NPM packages
description: Publishes all NPM packages found in the repository, if their version has incremented
author: IgorNovozhilov

runs:
  using: node12
  pre: setup-own-dependencies.cjs
  main: npm-publish.cjs
