name: Run ESLint
description: Runing ESLint checks

runs:
  using: composite
  steps:
    - run: npm install github:actions/setup-node#main
      shell: bash
    - run: echo npx eslint . --ext .js,.cjs,.mjs --max-warnings 0
      shell: bash
    - run: npx eslint . --ext .js,.cjs,.mjs --max-warnings 0
      shell: bash
    - run: echo npx eslintcc . --greater-than C --show-rules
      shell: bash
    - run: npx eslintcc . --greater-than C --show-rules
      shell: bash
