name: "Setup Node.js environment <extended>"
description: Setup a latest Node.js environment, dependencies.
  Extends <https://github.com/actions/setup-node>
author: IgorNovozhilov

# copy: https://github.com/actions/setup-node/blob/main/action.yml
inputs:
  always-auth:
    description: "Set always-auth in npmrc"
    required: false
    default: "false"
  node-version:
    description: "Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0"
    required: false
  architecture:
    description: "Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default."
    required: false
  check-latest:
    description: "Set this option if you want the action to check for the latest available version that satisfies the version spec"
    required: false
    default: "false"
  registry-url:
    description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN"
    required: false
  scope:
    description: "Optional scope for authenticating against scoped registries"
    required: false
  token:
    description: Used to pull node distributions from node-versions.  Since there's a default, this is typically not supplied by the user.
    required: false
    default: ${{ github.token }}

runs:
  using: "node12"
  pre: "setup-own-dependencies.cjs"
  main: "setup-node-latest.cjs"
