name: Run ESLint
description: Runing ESLint checks

runs:
  using: composite
  steps:
    - run: echo npx eslint . --ext .js,.cjs,.mjs --max-warnings 0
      shell: bash
    - run: npx eslint . --ext .js,.cjs,.mjs --max-warnings 0
      shell: bash
