name: Checks & Tests

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Checks with Linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ">=14"
          check-latest: true
      - run: npm install

      - uses: ./eslint
