name: Checks & Tests

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Checks with Linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/setup-node-latest@init-config
      - uses: nodutilus/project-config/setup-npm@init-config
      - uses: nodutilus/project-config/eslint@init-config
