name: Checks & Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks with Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@init-config
      - uses: nodutilus/project-config/actions/setup-npm@init-config
      - uses: nodutilus/project-config/actions/eslint@init-config
      - uses: nodutilus/project-config/actions/eslintcc@init-config

  tests:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@init-config
      - uses: nodutilus/project-config/actions/setup-npm@init-config
      - uses: nodutilus/project-config/actions/test@init-config

  coverage:
    name: Check Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: nodutilus/project-config/actions/setup-node-latest@init-config
      - uses: nodutilus/project-config/actions/setup-npm@init-config
      - uses: nodutilus/project-config/actions/nyc@init-config
